/**
 * Vue Publisher JSX runtime components.
 *
 * @packageDocumentation
 */
import {
    Fragment,
    defineComponent,
    h,
    type PropType,
    type VNodeChild
} from "vue";
import type {Publisher} from "reactor-core-ts";
import {isPublisher} from "@/shared/is-publisher.js";
import {isLazyJsxValue, lazyJsxValue, lazyJsxValueKey} from "@/shared/lazy-jsx-value.js";
import {mapMappable} from "@/shared/mappable.js";
import type {PublisherKeySelector, PublisherSnapshot} from "@/shared/types.js";
import {usePublisherSnapshot} from "@/vue/use-publisher-values.js";

/** Direct Publisher child generated by the JSX compiler. */
export const PublisherChild = defineComponent({
    name: "ReactorPublisherChild",
    props: {
        source: {type: null as unknown as PropType<unknown>, required: true},
        mode: {type: String as PropType<"append" | "latest">, default: "append"},
        lazy: {type: Boolean, default: false}
    },
    setup(props) {
        const snapshot = usePublisherSnapshot<unknown>(
            () => isPublisher<unknown>(props.source) ? props.source : undefined,
            () => props.mode,
            () => props.mode === "append" ? directChildKey : undefined
        );
        return (): VNodeChild => {
            if (!isPublisher(props.source)) {
                return renderOrdinaryChild(props.source, props.lazy);
            }
            return renderSnapshot(snapshot.value, renderDirectValue);
        };
    }
});

/** Mapped Publisher sequence generated by the JSX compiler. */
export const PublisherSequence = defineComponent({
    name: "ReactorPublisherSequence",
    props: {
        source: {type: null as unknown as PropType<unknown>, required: true},
        mode: {
            type: String as PropType<"incremental" | "latest" | "snapshot">,
            required: true
        },
        render: {
            type: Function as PropType<(value: unknown) => VNodeChild>,
            required: true
        },
        fallbackRender: {
            type: Function as PropType<(value: unknown) => unknown>,
            required: true
        },
        keyBy: Function as PropType<PublisherKeySelector<unknown>>
    },
    setup(props) {
        const snapshot = usePublisherSnapshot<unknown>(
            () => isPublisher<unknown | readonly unknown[]>(props.source) ? props.source : undefined,
            () => props.mode === "incremental" ? "append" : props.mode,
            () => props.keyBy
        );
        return (): VNodeChild => {
            if (!isPublisher(props.source)) {
                return mapMappable(props.source, props.fallbackRender) as VNodeChild;
            }
            return renderSnapshot(snapshot.value, props.render);
        };
    }
});

/** Compiler helper for JSX returned directly from Reactor flatMap. */
export {lazyJsxValue};

/** Renders an immutable snapshot with framework-safe internal keys. */
function renderSnapshot<T>(
    snapshot: PublisherSnapshot<T>,
    render: (value: T) => VNodeChild
): VNodeChild[] {
    if (snapshot.failure) {
        throw snapshot.failure.error;
    }
    return snapshot.entries.map(entry => h(Fragment, {key: entry.id}, [render(entry.value)]));
}

/** Renders a normal value or invokes a lazy JSX factory. */
function renderDirectValue(value: unknown): VNodeChild {
    return (isLazyJsxValue(value) ? value.render() : value) as VNodeChild;
}

/** Preserves Array.flatMap semantics when a statically ambiguous source is not a Publisher. */
function renderOrdinaryChild(value: unknown, lazy: boolean): VNodeChild {
    if (!lazy || !Array.isArray(value)) {
        return value as VNodeChild;
    }
    return value.map((item, index) => h(Fragment, {key: index}, [renderDirectValue(item)]));
}

/** Uses a lazy root key when present and a unique append key otherwise. */
function directChildKey(value: unknown): unknown {
    return isLazyJsxValue(value) && value.key !== undefined
        ? lazyJsxValueKey(value)
        : Symbol("Publisher.append");
}
