/**
 * Vue Publisher JSX runtime components.
 *
 * @packageDocumentation
 */
import {
    Fragment,
    defineComponent,
    h,
    type PropType,
    type VNodeChild
} from "vue";
import type {Publisher} from "reactor-core-ts";
import {containsPublisher, isPublisher} from "@/shared/is-publisher.js";
import {isLazyJsxValue, lazyJsxValue, lazyJsxValueKey} from "@/shared/lazy-jsx-value.js";
import {mapMappable} from "@/shared/mappable.js";
import {unkeyedPublisherKey} from "@/shared/keys.js";
import {assertPublisherHostSupported} from "@/shared/publisher-host.js";
import type {PublisherKeySelector, PublisherSnapshot} from "@/shared/types.js";
import {usePublisherSnapshot} from "@/vue/use-publisher-values.js";

/** Shared empty mapper context for non-contextual Publisher renderers. */
const EMPTY_RENDER_VALUES: readonly never[] = [];

/** Direct Publisher child generated by the JSX compiler. */
export const PublisherChild = defineComponent({
    name: "ReactorPublisherChild",
    props: {
        source: {type: null as unknown as PropType<unknown>, required: true},
        mode: {type: String as PropType<"append" | "latest">, default: "append"},
        lazy: {type: Boolean, default: false},
        unsupportedHost: String
    },
    setup(props) {
        const snapshot = usePublisherSnapshot<unknown>(
            () => isPublisher<unknown>(props.source) ? props.source : undefined,
            () => props.mode,
            () => props.mode === "append" ? directChildKey : undefined
        );
        return (): VNodeChild => {
            if (!isPublisher(props.source)) {
                return renderOrdinaryChild(props.source, props.lazy, props.unsupportedHost);
            }
            assertPublisherHostSupported(props.unsupportedHost);
            return renderSnapshot(snapshot.value, value => renderOrdinaryChild(
                renderDirectValue(value),
                false,
                props.unsupportedHost
            ));
        };
    }
});

/** Mapped Publisher sequence generated by the JSX compiler. */
export const PublisherSequence = defineComponent({
    name: "ReactorPublisherSequence",
    props: {
        source: {type: null as unknown as PropType<unknown>, required: true},
        mode: {
            type: String as PropType<"incremental" | "latest" | "snapshot">,
            required: true
        },
        render: {
            type: Function as PropType<(
                value: unknown,
                index: number,
                values: readonly unknown[]
            ) => unknown>,
            required: true
        },
        fallbackRender: {
            type: Function as PropType<(
                value: unknown,
                index: number,
                values: readonly unknown[]
            ) => unknown>,
            required: true
        },
        keyBy: Function as PropType<PublisherKeySelector<unknown>>,
        contextual: {type: Boolean, default: false},
        unsupportedHost: String
    },
    setup(props) {
        const snapshot = usePublisherSnapshot<unknown>(
            () => isPublisher<unknown | readonly unknown[]>(props.source) ? props.source : undefined,
            () => props.mode === "incremental" ? "append" : props.mode,
            () => props.keyBy
        );
        return (): VNodeChild => {
            if (!isPublisher(props.source)) {
                return renderOrdinaryChild(
                    mapMappable(props.source, props.fallbackRender),
                    false,
                    props.unsupportedHost
                );
            }
            assertPublisherHostSupported(props.unsupportedHost);
            return renderSnapshot(snapshot.value, (value, index, values) => renderOrdinaryChild(
                props.render(value, index, values),
                false,
                props.unsupportedHost
            ), props.contextual);
        };
    }
});

/** Compiler fast path returning ordinary children without a Vue component instance. */
export function renderPublisherChild(
    source: unknown,
    mode: "append" | "latest" = "append",
    lazy = false,
    unsupportedHost?: string
): VNodeChild {
    if (!isPublisher(source)) {
        return renderOrdinaryChild(source, lazy, unsupportedHost);
    }
    assertPublisherHostSupported(unsupportedHost);
    return h(PublisherChild, {
        source,
        mode,
        lazy,
        ...(unsupportedHost === undefined ? {} : {unsupportedHost})
    });
}

/** Compiler fast path returning ordinary mapped values without a Vue component. */
export function renderPublisherSequence(
    props: PublisherSequenceRuntimeProps,
    unsupportedHost?: string
): VNodeChild {
    if (!isPublisher(props.source)) {
        return renderOrdinaryChild(
            mapMappable(props.source, props.fallbackRender),
            false,
            unsupportedHost
        );
    }
    assertPublisherHostSupported(unsupportedHost);
    return h(PublisherSequence, {
        ...props,
        ...(unsupportedHost === undefined ? {} : {unsupportedHost})
    });
}

/** Props materialized by the mapped-value compiler fast path. */
interface PublisherSequenceRuntimeProps {
    /** Publisher candidate or ordinary mappable source. */
    readonly source: unknown;
    /** Reconciliation mode inferred from JSX shape. */
    readonly mode: "incremental" | "latest" | "snapshot";
    /** Publisher value renderer. */
    readonly render: (value: unknown, index: number, values: readonly unknown[]) => unknown;
    /** Native mapper retained for ordinary values. */
    readonly fallbackRender: (
        value: unknown,
        index: number,
        values: readonly unknown[]
    ) => unknown;
    /** Optional application reconciliation key. */
    readonly keyBy?: PublisherKeySelector<unknown>;
    /** Whether rendering observes snapshot index or array context. */
    readonly contextual?: boolean;
    /** Text-only host reported by the compiler for runtime validation. */
    readonly unsupportedHost?: string;
}

/** Compiler helper for JSX returned directly from Reactor flatMap. */
export {lazyJsxValue};

/** Renders an immutable snapshot with framework-safe internal keys. */
function renderSnapshot<T>(
    snapshot: PublisherSnapshot<T>,
    render: (value: T, index: number, values: readonly T[]) => VNodeChild,
    includeContext = false
): VNodeChild[] {
    if (snapshot.failure) {
        throw snapshot.failure.error;
    }
    const values = includeContext
        ? snapshot.entries.map(entry => entry.value)
        : EMPTY_RENDER_VALUES;
    return snapshot.entries.map((entry, index) => h(
        Fragment,
        {key: entry.id},
        [render(entry.value, index, values)]
    ));
}

/** Renders a normal value or invokes a lazy JSX factory. */
function renderDirectValue(value: unknown): VNodeChild {
    return (isLazyJsxValue(value) ? value.render() : value) as VNodeChild;
}

/** Preserves Array.flatMap semantics when a statically ambiguous source is not a Publisher. */
function renderOrdinaryChild(value: unknown, lazy: boolean, unsupportedHost?: string): VNodeChild {
    if (isPublisher(value)) {
        assertPublisherHostSupported(unsupportedHost);
        return h(PublisherChild, {
            source: value,
            ...(unsupportedHost === undefined ? {} : {unsupportedHost})
        });
    }
    if (!Array.isArray(value)) {
        return value as VNodeChild;
    }
    if (lazy) {
        return value.map(renderDirectValue);
    }
    return containsPublisher(value)
        ? renderPublisherArray(value, unsupportedHost)
        : value as VNodeChild;
}

/** Preserves ordinary VNodes and creates Vue bindings only for Publisher entries. */
function renderPublisherArray(values: readonly unknown[], unsupportedHost?: string): VNodeChild[] {
    return values.map((item, index) => {
        if (Array.isArray(item)) {
            return renderPublisherArray(item, unsupportedHost);
        }
        if (!isPublisher(item)) {
            return item as VNodeChild;
        }
        assertPublisherHostSupported(unsupportedHost);
        return h(PublisherChild, {source: item, key: `reactor-publisher:${index}`});
    });
}

/** Uses a lazy root key when present and a unique append key otherwise. */
function directChildKey(value: unknown): unknown {
    return isLazyJsxValue(value) && value.key !== undefined
        ? lazyJsxValueKey(value)
        : unkeyedPublisherKey(value);
}
