/**
 * Shared component logic for hook-based virtual DOM frameworks.
 *
 * @packageDocumentation
 */
import type {Publisher} from "reactor-core-ts";
import {containsPublisher, isPublisher} from "@/shared/is-publisher.js";
import {isLazyJsxValue, lazyJsxValue, lazyJsxValueKey} from "@/shared/lazy-jsx-value.js";
import {mapMappable} from "@/shared/mappable.js";
import {unkeyedPublisherKey} from "@/shared/keys.js";
import {assertPublisherHostSupported} from "@/shared/publisher-host.js";
import {PublisherExternalStore} from "@/shared/publisher-store.js";
import type {PublisherSnapshotItem, PublisherValue} from "@/shared/publisher-value.js";
import type {
    PublisherKeySelector,
    PublisherRenderMode,
    PublisherSnapshot
} from "@/shared/types.js";

/** Shared empty mapper context for direct Publisher children. */
const EMPTY_RENDER_VALUES: readonly never[] = [];

/** Hook and VNode operations supplied by React or Preact. */
export interface HookRendererAdapter<Node> {
    /** Framework fragment component. */
    readonly Fragment: unknown;
    /** Creates a framework VNode. */
    readonly createElement: (type: unknown, props: Record<string, unknown> | null, ...children: unknown[]) => Node;
    /** Memoizes a value by dependencies. */
    readonly useMemo: <T>(factory: () => T, dependencies: readonly unknown[]) => T;
    /** Commits mutable store configuration only after the framework accepts a render. */
    readonly useCommitEffect: (effect: () => void, dependencies: readonly unknown[]) => void;
    /** Reads and subscribes to an optional Publisher external store. */
    readonly usePublisherSnapshot: <T>(store: PublisherExternalStore<T> | undefined) => PublisherSnapshot<T>;
}

/** Direct Publisher JSX child props generated by the compiler. */
export interface PublisherChildProps {
    /** Publisher candidate or ordinary child value. */
    readonly source: unknown;
    /** Append all emissions or retain only the latest. */
    readonly mode?: "append" | "latest";
    /** Whether an ordinary array contains lazy flatMap descriptors. */
    readonly lazy?: boolean;
    /** Text-only host reported by the compiler for runtime validation. */
    readonly unsupportedHost?: string;
}

/** Mapped Publisher sequence props generated by the compiler. */
export interface PublisherSequenceProps<T> {
    /** Publisher candidate or ordinary mappable source. */
    readonly source: unknown;
    /** Incremental, latest, or authoritative snapshot behavior. */
    readonly mode: "incremental" | "latest" | "snapshot";
    /** Renderer with the Publisher key removed. */
    readonly render: (value: T, index: number, values: readonly T[]) => unknown;
    /** Original mapper used for ordinary sources. */
    readonly fallbackRender: (
        value: unknown,
        index: number,
        values: readonly unknown[]
    ) => unknown;
    /** Optional Publisher reconciliation key. */
    readonly keyBy?: PublisherKeySelector<T>;
    /** Whether the renderer consumes snapshot index or array context. */
    readonly contextual?: boolean;
    /** Text-only host reported by the compiler for runtime validation. */
    readonly unsupportedHost?: string;
}

/** Options accepted by hook-based Publisher value integrations. */
export interface UsePublisherAppendOptions<T> {
    /** Append, latest, or authoritative snapshot mode. */
    readonly mode?: Exclude<PublisherRenderMode, "snapshot">;
    /** Optional stable key selector. */
    readonly keyBy?: PublisherKeySelector<T>;
}

/** Options requiring an authoritative array Publisher. */
export interface UsePublisherSnapshotOptions<T> {
    /** Selects authoritative snapshot reconciliation. */
    readonly mode: "snapshot";
    /** Optional stable key selector. */
    readonly keyBy?: PublisherKeySelector<T>;
}

/** Options accepted by hook-based Publisher value integrations. */
export type UsePublisherOptions<T> = UsePublisherAppendOptions<T> | UsePublisherSnapshotOptions<T>;

/** Type-safe hook overloads separating item and snapshot Publishers. */
export interface UsePublisherValues {
    /** Reads append/latest item emissions. */
    <Source extends Publisher<unknown>>(
        source: Source,
        options?: UsePublisherAppendOptions<PublisherValue<Source>>
    ): readonly PublisherValue<Source>[];
    /** Reads authoritative array emissions. */
    <Source extends Publisher<readonly unknown[]>>(
        source: Source,
        options: UsePublisherSnapshotOptions<PublisherSnapshotItem<Source>>
    ): readonly PublisherSnapshotItem<Source>[];
}

/** Hook-based Publisher runtime components. */
export interface HookPublisherComponents<Node> {
    /** Direct Publisher child component. */
    readonly PublisherChild: (props: PublisherChildProps) => Node | unknown;
    /** Mapped Publisher sequence component. */
    readonly PublisherSequence: <T>(props: PublisherSequenceProps<T>) => Node | unknown;
    /** Fast compiler path avoiding a framework component for ordinary values. */
    readonly renderPublisherChild: (
        source: unknown,
        mode?: "append" | "latest",
        lazy?: boolean,
        unsupportedHost?: string
    ) => Node | unknown;
    /** Fast compiler path avoiding a component for ordinary mapped values. */
    readonly renderPublisherSequence: <T>(
        props: PublisherSequenceProps<T>,
        unsupportedHost?: string
    ) => Node | unknown;
    /** Hook exposing reconciled Publisher values. */
    readonly usePublisherValues: UsePublisherValues;
}

/** Creates React/Preact runtime components without duplicating lifecycle code. */
export function createHookPublisherComponents<Node>(
    adapter: HookRendererAdapter<Node>
): HookPublisherComponents<Node> {
    /** Renders a direct Publisher or preserves an ordinary child. */
    function PublisherChild(props: PublisherChildProps): Node | unknown {
        const source = props.source;
        const publisher = isPublisher<unknown>(source) ? source : undefined;
        const mode = props.mode ?? "append";
        const store = adapter.useMemo(
            () => publisher
                ? new PublisherExternalStore(
                    publisher,
                    mode,
                    mode === "append" ? directChildKey : undefined
                )
                : undefined,
            [publisher, mode]
        );
        const snapshot = adapter.usePublisherSnapshot(store);
        if (!publisher) {
            return renderOrdinaryChild(source, props.lazy === true, props.unsupportedHost);
        }
        assertPublisherHostSupported(props.unsupportedHost);
        return renderSnapshot(snapshot, (value: unknown) => renderOrdinaryChild(
            renderDirectValue(value),
            false,
            props.unsupportedHost
        ));
    }

    /** Renders a mapped Publisher or preserves an ordinary mappable source. */
    function PublisherSequence<T>(props: PublisherSequenceProps<T>): Node | unknown {
        const publisher = isPublisher<T | readonly T[]>(props.source) ? props.source : undefined;
        const mode = props.mode === "incremental" ? "append" : props.mode;
        const store = adapter.useMemo(
            () => publisher
                ? new PublisherExternalStore<T>(publisher, mode, props.keyBy)
                : undefined,
            [publisher, mode]
        );
        adapter.useCommitEffect(() => store?.setKeyBy(props.keyBy), [store, props.keyBy]);
        const snapshot = adapter.usePublisherSnapshot(store);
        if (!publisher) {
            return renderOrdinaryChild(
                mapMappable(props.source, props.fallbackRender),
                false,
                props.unsupportedHost
            );
        }
        assertPublisherHostSupported(props.unsupportedHost);
        return renderSnapshot(snapshot, (value, index, values) => renderOrdinaryChild(
            props.render(value, index, values),
            false,
            props.unsupportedHost
        ), props.contextual === true);
    }

    /** Subscribes through framework hooks and caches the materialized value array. */
    function usePublisherValues<Source extends Publisher<unknown>>(
        source: Source,
        options?: UsePublisherAppendOptions<PublisherValue<Source>>
    ): readonly PublisherValue<Source>[];
    function usePublisherValues<Source extends Publisher<readonly unknown[]>>(
        source: Source,
        options: UsePublisherSnapshotOptions<PublisherSnapshotItem<Source>>
    ): readonly PublisherSnapshotItem<Source>[];
    /** Implements both item and authoritative snapshot overloads. */
    function usePublisherValues(
        source: Publisher<unknown | readonly unknown[]>,
        options: UsePublisherOptions<never> = {}
    ): readonly unknown[] {
        const mode = options.mode ?? "append";
        const store = adapter.useMemo(
            () => new PublisherExternalStore<unknown>(
                source,
                mode,
                options.keyBy as PublisherKeySelector<unknown> | undefined
            ),
            [source, mode]
        );
        adapter.useCommitEffect(
            () => store.setKeyBy(options.keyBy as PublisherKeySelector<unknown> | undefined),
            [store, options.keyBy]
        );
        const snapshot = adapter.usePublisherSnapshot(store);
        return adapter.useMemo(() => {
            if (snapshot.failure) {
                throw snapshot.failure.error;
            }
            return snapshot.entries.map(entry => entry.value);
        }, [snapshot]);
    }

    /** Returns ordinary values directly and allocates a component only for a Publisher. */
    function renderPublisherChild(
        source: unknown,
        mode: "append" | "latest" = "append",
        lazy = false,
        unsupportedHost?: string
    ): Node | unknown {
        if (!isPublisher(source)) {
            return renderOrdinaryChild(source, lazy, unsupportedHost);
        }
        assertPublisherHostSupported(unsupportedHost);
        return adapter.createElement(PublisherChild, {source, mode, lazy, unsupportedHost});
    }

    /** Returns an ordinary mapped value directly and allocates only for a Publisher. */
    function renderPublisherSequence<T>(
        props: PublisherSequenceProps<T>,
        unsupportedHost?: string
    ): Node | unknown {
        if (!isPublisher(props.source)) {
            return renderOrdinaryChild(
                mapMappable(props.source, props.fallbackRender),
                false,
                unsupportedHost
            );
        }
        assertPublisherHostSupported(unsupportedHost);
        return adapter.createElement(
            PublisherSequence,
            {...props, unsupportedHost} as unknown as Record<string, unknown>
        );
    }

    /** Converts one immutable store snapshot into keyed framework fragments. */
    function renderSnapshot<T>(
        snapshot: PublisherSnapshot<T>,
        render: (value: T, index: number, values: readonly T[]) => unknown,
        includeContext = false
    ): Node[] {
        if (snapshot.failure) {
            throw snapshot.failure.error;
        }
        const values = includeContext
            ? snapshot.entries.map(entry => entry.value)
            : EMPTY_RENDER_VALUES;
        return snapshot.entries.map((entry, index) => adapter.createElement(
            adapter.Fragment,
            {key: entry.id},
            render(entry.value, index, values)
        ));
    }

    /** Restores native direct-child behavior for a non-Publisher value. */
    function renderOrdinaryChild(value: unknown, lazy: boolean, unsupportedHost?: string): unknown {
        if (isPublisher(value)) {
            assertPublisherHostSupported(unsupportedHost);
            return adapter.createElement(PublisherChild, {source: value});
        }
        if (!Array.isArray(value)) {
            return value;
        }
        if (lazy) {
            return value.map(renderDirectValue);
        }
        return containsPublisher(value) ? renderPublisherArray(value, unsupportedHost) : value;
    }

    /** Preserves ordinary children and creates bindings only for nested Publishers. */
    function renderPublisherArray(values: readonly unknown[], unsupportedHost?: string): unknown[] {
        return values.map((item, index) => {
            if (Array.isArray(item)) {
                return renderPublisherArray(item, unsupportedHost);
            }
            if (!isPublisher(item)) {
                return item;
            }
            assertPublisherHostSupported(unsupportedHost);
            return adapter.createElement(PublisherChild, {
                source: item,
                key: `reactor-publisher:${index}`
            });
        });
    }

    return {
        PublisherChild,
        PublisherSequence,
        renderPublisherChild,
        renderPublisherSequence,
        usePublisherValues
    };
}

/** Compiler runtime helper re-exported by every JSX framework module. */
export {lazyJsxValue};

/** Renders a normal value or invokes a lazy JSX factory. */
function renderDirectValue(value: unknown): unknown {
    return isLazyJsxValue(value) ? value.render() : value;
}

/** Uses a lazy root key when present and a unique append key otherwise. */
function directChildKey(value: unknown): unknown {
    return isLazyJsxValue(value) && value.key !== undefined
        ? lazyJsxValueKey(value)
        : unkeyedPublisherKey(value);
}
