/**
 * Shared component logic for hook-based virtual DOM frameworks.
 *
 * @packageDocumentation
 */
import type {Publisher} from "reactor-core-ts";
import {isPublisher} from "@/shared/is-publisher.js";
import {isLazyJsxValue, lazyJsxValue, lazyJsxValueKey} from "@/shared/lazy-jsx-value.js";
import {mapMappable} from "@/shared/mappable.js";
import {PublisherExternalStore} from "@/shared/publisher-store.js";
import type {
    PublisherKeySelector,
    PublisherRenderMode,
    PublisherSnapshot
} from "@/shared/types.js";

/** Hook and VNode operations supplied by React or Preact. */
export interface HookRendererAdapter<Node> {
    /** Framework fragment component. */
    readonly Fragment: unknown;
    /** Creates a framework VNode. */
    readonly createElement: (type: unknown, props: Record<string, unknown> | null, ...children: unknown[]) => Node;
    /** Memoizes a value by dependencies. */
    readonly useMemo: <T>(factory: () => T, dependencies: readonly unknown[]) => T;
    /** Reads and subscribes to an optional Publisher external store. */
    readonly usePublisherSnapshot: <T>(store: PublisherExternalStore<T> | undefined) => PublisherSnapshot<T>;
}

/** Direct Publisher JSX child props generated by the compiler. */
export interface PublisherChildProps {
    /** Publisher candidate or ordinary child value. */
    readonly source: unknown;
    /** Append all emissions or retain only the latest. */
    readonly mode?: "append" | "latest";
    /** Whether an ordinary array contains lazy flatMap descriptors. */
    readonly lazy?: boolean;
}

/** Mapped Publisher sequence props generated by the compiler. */
export interface PublisherSequenceProps<T> {
    /** Publisher candidate or ordinary mappable source. */
    readonly source: unknown;
    /** Incremental, latest, or authoritative snapshot behavior. */
    readonly mode: "incremental" | "latest" | "snapshot";
    /** Renderer with the Publisher key removed. */
    readonly render: (value: T) => unknown;
    /** Original mapper used for ordinary sources. */
    readonly fallbackRender: (value: unknown) => unknown;
    /** Optional Publisher reconciliation key. */
    readonly keyBy?: PublisherKeySelector<T>;
}

/** Options accepted by hook-based Publisher value integrations. */
export interface UsePublisherOptions<T> {
    /** Append, latest, or authoritative snapshot mode. */
    readonly mode?: PublisherRenderMode;
    /** Optional stable key selector. */
    readonly keyBy?: PublisherKeySelector<T>;
}

/** Hook-based Publisher runtime components. */
export interface HookPublisherComponents<Node> {
    /** Direct Publisher child component. */
    readonly PublisherChild: (props: PublisherChildProps) => Node | unknown;
    /** Mapped Publisher sequence component. */
    readonly PublisherSequence: <T>(props: PublisherSequenceProps<T>) => Node | unknown;
    /** Hook exposing reconciled Publisher values. */
    readonly usePublisherValues: <T>(
        source: Publisher<T | readonly T[]>,
        options?: UsePublisherOptions<T>
    ) => readonly T[];
}

/** Creates React/Preact runtime components without duplicating lifecycle code. */
export function createHookPublisherComponents<Node>(
    adapter: HookRendererAdapter<Node>
): HookPublisherComponents<Node> {
    /** Renders a direct Publisher or preserves an ordinary child. */
    function PublisherChild(props: PublisherChildProps): Node | unknown {
        const source = props.source;
        const publisher = isPublisher<unknown>(source) ? source : undefined;
        const mode = props.mode ?? "append";
        const store = adapter.useMemo(
            () => publisher
                ? new PublisherExternalStore(
                    publisher,
                    mode,
                    mode === "append" ? directChildKey : undefined
                )
                : undefined,
            [publisher, mode]
        );
        const snapshot = adapter.usePublisherSnapshot(store);
        if (!publisher) {
            return renderOrdinaryChild(source, props.lazy === true);
        }
        return renderSnapshot(snapshot, renderDirectValue);
    }

    /** Renders a mapped Publisher or preserves an ordinary mappable source. */
    function PublisherSequence<T>(props: PublisherSequenceProps<T>): Node | unknown {
        const publisher = isPublisher<T | readonly T[]>(props.source) ? props.source : undefined;
        const mode = props.mode === "incremental" ? "append" : props.mode;
        const store = adapter.useMemo(
            () => publisher
                ? new PublisherExternalStore<T>(publisher, mode, props.keyBy)
                : undefined,
            [publisher, mode, props.keyBy]
        );
        const snapshot = adapter.usePublisherSnapshot(store);
        if (!publisher) {
            return mapMappable(props.source, props.fallbackRender);
        }
        return renderSnapshot(snapshot, props.render);
    }

    /** Subscribes through framework hooks and caches the materialized value array. */
    function usePublisherValues<T>(
        source: Publisher<T | readonly T[]>,
        options: UsePublisherOptions<T> = {}
    ): readonly T[] {
        const mode = options.mode ?? "append";
        const store = adapter.useMemo(
            () => new PublisherExternalStore(source, mode, options.keyBy),
            [source, mode, options.keyBy]
        );
        const snapshot = adapter.usePublisherSnapshot(store);
        return adapter.useMemo(() => {
            if (snapshot.failure) {
                throw snapshot.failure.error;
            }
            return snapshot.entries.map(entry => entry.value);
        }, [snapshot]);
    }

    /** Converts one immutable store snapshot into keyed framework fragments. */
    function renderSnapshot<T>(snapshot: PublisherSnapshot<T>, render: (value: T) => unknown): Node[] {
        if (snapshot.failure) {
            throw snapshot.failure.error;
        }
        return snapshot.entries.map(entry => adapter.createElement(
            adapter.Fragment,
            {key: entry.id},
            render(entry.value)
        ));
    }

    /** Restores native direct-child behavior for a non-Publisher value. */
    function renderOrdinaryChild(value: unknown, lazy: boolean): unknown {
        if (!lazy || !Array.isArray(value)) {
            return value;
        }
        return value.map((item, index) => adapter.createElement(
            adapter.Fragment,
            {key: index},
            renderDirectValue(item)
        ));
    }

    return {PublisherChild, PublisherSequence, usePublisherValues};
}

/** Compiler runtime helper re-exported by every JSX framework module. */
export {lazyJsxValue};

/** Renders a normal value or invokes a lazy JSX factory. */
function renderDirectValue(value: unknown): unknown {
    return isLazyJsxValue(value) ? value.render() : value;
}

/** Uses a lazy root key when present and a unique append key otherwise. */
function directChildKey(value: unknown): unknown {
    return isLazyJsxValue(value) && value.key !== undefined
        ? lazyJsxValueKey(value)
        : Symbol("Publisher.append");
}
