/** Runtime component for mapped Solid Publisher values and list snapshots. */
import {batch, createRenderEffect, onCleanup, type JSX} from "solid-js";
import type {Publisher} from "reactor-core-ts";
import {isPublisher} from "@/shared/is-publisher.js";
import {latestPublisherKey} from "@/shared/keys.js";
import {assertPublisherHostSupported} from "@/shared/publisher-host.js";
import {mapMappable} from "@/shared/mappable.js";
import {subscribeToPublisher} from "@/shared/subscription.js";
import type {PublisherKeySelector} from "@/shared/types.js";
import {createRenderState} from "@/solid/runtime/render-state.js";
import {renderOrdinaryValue} from "@/solid/runtime/publisher-child.js";
import {SequenceState} from "@/solid/runtime/sequence-state.js";
import {requireSolidOwner} from "@/solid/runtime/solid-owner.js";

/** Solid sequence reconciliation strategy. */
export type PublisherSequenceMode = "incremental" | "latest" | "snapshot";

/** Props generated by the shared Publisher JSX compiler. */
export interface PublisherSequenceProps<T> {
    /** Publisher candidate or ordinary mappable source. */
    readonly source: unknown;
    /** Reconciliation strategy selected from JSX expression shape. */
    readonly mode: PublisherSequenceMode;
    /** Application mapper with its compiler-only key removed. */
    readonly render: (value: T, index: number, values: readonly T[]) => JSX.Element;
    /** Original mapper retained for ordinary source fallback. */
    readonly fallbackRender: (value: unknown, index: number, values: readonly unknown[]) => JSX.Element;
    /** Optional stable key selector extracted from JSX. */
    readonly keyBy?: PublisherKeySelector<T>;
    /** Whether rendering consumes authoritative index or array context. */
    readonly contextual?: boolean;
    /** Text-only host reported by the compiler for runtime validation. */
    readonly unsupportedHost?: string;
}

/** Renders mapped Publisher values through independently owned Solid roots. */
export function PublisherSequence<T>(props: PublisherSequenceProps<T>): JSX.Element {
    const owner = requireSolidOwner("PublisherSequence");
    const renderState = createRenderState();
    let sequence: SequenceState<T> | undefined;
    let previousSource: unknown;
    let previousMode: PublisherSequenceMode | undefined;
    let hasPreviousSource = false;
    let previousKeyBy: PublisherKeySelector<T> | undefined;
    let hasPreviousKeyBy = false;
    let appliedSnapshotKeyBy: PublisherKeySelector<T> | undefined;
    let hasAppliedSnapshotKeyBy = false;

    /** Lazily allocates fine-grained sequence state. */
    const getSequence = (): SequenceState<T> => {
        sequence ??= new SequenceState(owner, (value, index, values) => renderOrdinaryValue(
            props.render(value, index, values),
            false,
            props.unsupportedHost
        ), props.contextual === true);
        return sequence;
    };

    createRenderEffect(() => {
        const keyBy = props.keyBy;
        if (
            hasPreviousKeyBy && previousKeyBy !== keyBy && sequence &&
            props.mode === "incremental"
        ) {
            try {
                batch(() => {
                    sequence?.rekey(keyBy);
                    renderState.clear();
                });
            } catch (error) {
                renderState.reportFailure(error);
            }
        }
        previousKeyBy = keyBy;
        hasPreviousKeyBy = true;
    });

    createRenderEffect(() => {
        const source = props.source;
        const publisher = isPublisher<T | readonly T[]>(source) ? source : undefined;
        if (!publisher) {
            batch(() => {
                sequence?.clear();
                try {
                    renderState.showFallback(
                        renderOrdinaryValue(
                            mapMappable(source, props.fallbackRender),
                            false,
                            props.unsupportedHost
                        )
                    );
                } catch (error) {
                    renderState.reportFailure(error);
                }
            });
            previousSource = undefined;
            previousMode = undefined;
            hasPreviousSource = false;
            return;
        }

        assertPublisherHostSupported(props.unsupportedHost);

        const sourceChanged = hasPreviousSource && previousSource !== source;
        const modeChanged = previousMode !== undefined && previousMode !== props.mode;
        const activeSequence = getSequence();
        batch(() => {
            renderState.clear();
            if (modeChanged || (sourceChanged && props.mode !== "snapshot")) {
                activeSequence.clear();
                hasAppliedSnapshotKeyBy = false;
            }
        });
        previousSource = source;
        previousMode = props.mode;
        hasPreviousSource = true;
        let subscribing = true;
        let appliedSynchronousSnapshot = false;
        let active = true;
        const disposable = subscribeToPublisher(publisher, {
            next: value => {
                if (!active) {
                    return;
                }
                try {
                    batch(() => {
                        if (props.mode === "snapshot") {
                            if (!Array.isArray(value)) {
                                throw new TypeError("Snapshot Publisher must emit an array");
                            }
                            const keyBy = props.keyBy;
                            activeSequence.applySnapshot(
                                value,
                                keyBy,
                                hasAppliedSnapshotKeyBy && appliedSnapshotKeyBy !== keyBy
                            );
                            appliedSnapshotKeyBy = keyBy;
                            hasAppliedSnapshotKeyBy = true;
                            appliedSynchronousSnapshot ||= subscribing;
                        } else if (props.mode === "latest") {
                            activeSequence.append(value as T, latestPublisherKey);
                        } else {
                            activeSequence.append(value as T, props.keyBy);
                        }
                        renderState.clear();
                    });
                } catch (error) {
                    renderState.reportFailure(error);
                }
            },
            error: error => {
                if (active) {
                    active = false;
                    renderState.reportFailure(error);
                }
            },
            complete: () => {
                active = false;
            }
        });
        subscribing = false;
        if (sourceChanged && props.mode === "snapshot" && !appliedSynchronousSnapshot) {
            batch(() => {
                activeSequence.clear();
                hasAppliedSnapshotKeyBy = false;
            });
        }
        onCleanup(() => {
            active = false;
            disposable?.dispose();
        });
    });

    onCleanup(() => sequence?.clear());
    const output = () => {
        const override = renderState.current();
        if (override?.kind === "failure") {
            throw override.error;
        }
        return override?.kind === "fallback"
            ? override.value
            : sequence?.view() ?? [];
    };
    return output as unknown as JSX.Element;
}
