/** Runtime component for direct Solid Publisher children and lazy flatMap JSX. */
import {batch, createRenderEffect, onCleanup, type JSX} from "solid-js";
import type {Publisher} from "reactor-core-ts";
import {isPublisher} from "@/shared/is-publisher.js";
import {
    isLazyJsxValue,
    lazyJsxValueKey
} from "@/shared/lazy-jsx-value.js";
import {subscribeToPublisher} from "@/shared/subscription.js";
import type {PublisherKeySelector} from "@/shared/types.js";
import {latestPublisherKey} from "@/shared/keys.js";
import {createRenderState} from "@/solid/runtime/render-state.js";
import {SequenceState} from "@/solid/runtime/sequence-state.js";
import {requireSolidOwner} from "@/solid/runtime/solid-owner.js";

/** Reconciliation mode for a direct Publisher JSX child. */
export type PublisherChildMode = "append" | "latest";

/** Props generated by the shared Publisher JSX compiler. */
export interface PublisherChildProps {
    /** Publisher candidate or ordinary Solid child value. */
    readonly source: unknown;
    /** Whether emissions append or update one latest-value slot. */
    readonly mode?: PublisherChildMode;
    /** Whether an ordinary array contains compiler-generated lazy JSX. */
    readonly lazy?: boolean;
}

/** Renders a Publisher or passes through an ordinary Solid child expression. */
export function PublisherChild(props: PublisherChildProps): JSX.Element {
    const owner = requireSolidOwner("PublisherChild");
    const renderState = createRenderState();
    let sequence: SequenceState<unknown> | undefined;
    let previousPublisher: Publisher<unknown> | undefined;
    let previousMode: PublisherChildMode | undefined;

    /** Lazily allocates fine-grained sequence state. */
    const getSequence = (): SequenceState<unknown> => {
        sequence ??= new SequenceState(owner, asJsxElement);
        return sequence;
    };

    createRenderEffect(() => {
        const source = props.source;
        const mode = props.mode ?? "append";
        if (!isPublisher<unknown>(source)) {
            previousPublisher = undefined;
            previousMode = undefined;
            batch(() => {
                sequence?.clear();
                renderState.showFallback(renderOrdinaryValue(source, props.lazy === true));
            });
            return;
        }

        const activeSequence = getSequence();
        batch(() => {
            renderState.clear();
            if ((previousPublisher && previousPublisher !== source) ||
                (previousMode && previousMode !== mode)) {
                activeSequence.clear();
            }
        });
        previousPublisher = source;
        previousMode = mode;
        let active = true;
        const disposable = subscribeToPublisher(source, {
            next: value => {
                if (!active) {
                    return;
                }
                try {
                    batch(() => {
                        activeSequence.append(value, readKeyBy(mode, value));
                        renderState.clear();
                    });
                } catch (error) {
                    renderState.reportFailure(error);
                }
            },
            error: error => {
                if (active) {
                    active = false;
                    renderState.reportFailure(error);
                }
            },
            complete: () => {
                active = false;
            }
        });
        onCleanup(() => {
            active = false;
            disposable?.dispose();
        });
    });

    onCleanup(() => sequence?.clear());
    const output = () => {
        const override = renderState.current();
        if (override?.kind === "failure") {
            throw override.error;
        }
        return override?.kind === "fallback"
            ? override.value
            : sequence?.view() ?? [];
    };
    return output as unknown as JSX.Element;
}

/** Renders compiler-generated lazy values produced by an ordinary flatMap. */
function renderOrdinaryValue(value: unknown, lazy: boolean): JSX.Element {
    return lazy && Array.isArray(value)
        ? value.map(asJsxElement)
        : value as JSX.Element;
}

/** Converts a normal or compiler-generated lazy value to Solid JSX. */
function asJsxElement(value: unknown): JSX.Element {
    return isLazyJsxValue(value)
        ? value.render() as JSX.Element
        : value as JSX.Element;
}

/** Selects the key function for the current direct-child emission. */
function readKeyBy(
    mode: PublisherChildMode,
    value: unknown
): PublisherKeySelector<unknown> | undefined {
    if (mode === "latest") {
        return latestPublisherKey;
    }
    return isLazyJsxValue(value) && value.key !== undefined
        ? lazyJsxValueKey
        : undefined;
}
